server:
  port: 6011

spring:
  application:
    name: self-service-template-microservice
  datasource:
    hikari:
      maximum-pool-size: 5

  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
      enabled: true

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /api/v1/api-docs
