server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: self-service-file-microservice
          uri: lb://self-service-file-microservice
          predicates:
            - Path= /v1/api/uploader/**,/v1/api/file-services/**
        - id: self-service-template-microservice
          uri: lb://self-service-template-microservice
          predicates:
            - Path= /v1/api/template/**,/v1/api/data-processor**,/v1/api/oracle-db**,/v1/api/sanity-rules**,/v1/api/transformation-rules
        - id: self-service-user-management-microservice
          uri: lb://self-service-user-management-microservice
          predicates:
            - Path= /v1/api/user-mgmt/**

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username
