server:
  port: 8082
  servlet:
    contextPath: /cdcp-api-gateway-service
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: self-service-file-microservice
          uri: lb://self-service-file-microservice
          predicates:
            - Path= /ssp-file-mgmt-service/v1/api/uploader/**,/ssp-file-mgmt-service/v1/api/file-services/**
        - id: self-service-template-microservice
          uri: lb://self-service-template-microservice
          predicates:
            - Path= /ssp-template-service/v1/api/template/**,/ssp-template-service/v1/api/data-processor/**,/ssp-template-service/v1/api/sanity-rules/**,/ssp-template-service/v1/api/transformation-rules/**
        - id: self-service-user-management-microservice
          uri: lb://self-service-user-management-microservice
          predicates:
            - Path= /ssp-user-mgmt-service/v1/api/user-mgmt/**
        - id: self-service-oracle-template-microservice
          uri: lb://self-service-oracle-template-microservice
          predicates:
            - Path= /ssp-oracle-template-service/v1/api/oracle-db/**

info:
  application:
    webPortalOrigin: http://localhost:3000,http://20.219.56.2:30000,https://frontend-service-kislay99-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/
