eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 6012

spring:
  application:
    name: self-service-user-management-microservice
  datasource:
    hikari:
      #      connection-timeout: 3000000
      #      idle-timeout: 6000000
      maximum-pool-size: 5
  #      max-lifetime: 1800000
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
      enabled: true
  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://20.219.56.2:30435/auth/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username
springdoc:
  api-docs:
    path: /api/v1/api-docs
