server:
  port: 6012

spring:
  application:
    name: self-service-user-management-microservice
  datasource:
    hikari:
      maximum-pool-size: 5
  devtools:
    restart:
      enabled: true
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://20.219.56.2:30435/auth/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # dialect: org.hibernate.dialect.PostgreSQLDialect
    # hibernate:
    # ddl-auto: update
    show-sql: false

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username

springdoc:
  api-docs:
    path: /swagger/api/v1/api-docs
